<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <EnableWindowsTargeting>true</EnableWindowsTargeting>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <PlatformTarget>x64</PlatformTarget>
    <RootNamespace>AutoHitCounter</RootNamespace>
    <AssemblyName>AutoHitCounter</AssemblyName>
    <ApplicationIcon>Assets\icon.ico</ApplicationIcon>
    <LangVersion>12</LangVersion>
    <Nullable>disable</Nullable>
    <ImplicitUsings>disable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Costura.Fody" Version="6.0.0" PrivateAssets="all" />
    <PackageReference Include="Extended.Wpf.Toolkit" Version="5.0.0" />
    <PackageReference Include="Fleck" Version="1.2.0" />
    <PackageReference Include="Fody" Version="6.9.3" PrivateAssets="all" />
    <PackageReference Include="H.Hooks" Version="2.1.0-dev.26" />
    <PackageReference Include="System.Text.Encoding.CodePages" Version="8.0.0" />
  </ItemGroup>

  <ItemGroup>
    <None Include="FodyWeavers.xml" />
  </ItemGroup>
</Project>
